### ISSUE TITLE
HP 시스템 구현

### ISSUE THREAD

**Issue by SpiceSoy** [SpiceSoy/KPU-2DGP-RhythmCrush#6]
- [x] HP 0 될시에 따른 게임 오버 구현 #5 
- [x] 노트 판정에 따른 HP 가, 감 구현 #4  #1 
- [x] HP UI 구현 #5

**Comment by SpiceSoy** [comment]
ef6be7bd1d23029a3752742883c8af4aa275fa06
구현 완료
